Fix search_path race by separating commands way
postgis/docker-postgis pull request #297
Opened 2022-06-06 09:47 UTC by sanak

Closes #296

@ImreSamu (CC: @strk)
I create this PR with the following steps, so could you check this ?

Note that my environment is macOS Monterey M1 (Apple Silicon) with zsh, so I couldn't execute `make test` due to No.3 error.

1. Apply #266 description's following diff.
   > The following diff is my suggestion, but I am not sure whether the sessions are separated and original #290 issue will be solved by this.
   ```diff
   --- a/initdb-postgis.sh
   +++ b/initdb-postgis.sh
           "${psql[@]}" --dbname="$DB" <<-'EOSQL'
                   CREATE EXTENSION IF NOT EXISTS postgis;
                   CREATE EXTENSION IF NOT EXISTS postgis_topology;
   -               -- Reconnect to update pg_setting.resetval
   -               -- See https://github.com/postgis/docker-postgis/issues/288
   -               \c
   +EOSQL
   +
   +       "${psql[@]}" --dbname="$DB" <<-'EOSQL'
                   CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
                   CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
    EOSQL
   ```
2. Execute `make update` to apply above changes.
3. Execute `make test` with setting environment variables, but encounter the following bash error.
   ```zsh
   % export VERSION=14-3.2
   % export VARIANT=default
   % make test
   :
   testing postgis/postgis:14-3.2
	'utc' [1/3]...passed
	'no-hard-coded-passwords' [2/3].../Users/sanak/official-images/test/tests/no-hard-coded-passwords/run.sh: line 12: declare: -A: invalid option
   declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
   failed
   :
   ```
4. Build image from command line.
   ```zsh
   % docker build --pull --no-cache -t postgis/postgis:14-3.2 14-3.2
   ```
5. Check whether search_path is still valid.
   ```zsh
   % docker run --name some-postgis -e POSTGRES_PASSWORD=mysecretpassword -d postgis/postgis:14-3.2
   % docker exec -ti some-postgis psql -U postgres
   psql (14.3 (Debian 14.3-1.pgdg110+1))
   Type "help" for help.
   
   postgres=# show search_path;
              search_path            
   ----------------------------------
    "$user", public, topology, tiger
   (1 row)
   ```
6. Check whether reconnecting is not happen. (Comparing with https://github.com/postgis/docker-postgis/pull/292#issue-1197169442 - debian log)
   ```zsh
   /usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/10_postgis.sh
   CREATE DATABASE
   Loading PostGIS extensions into template_postgis
   CREATE EXTENSION
   CREATE EXTENSION
   CREATE EXTENSION
   CREATE EXTENSION
   Loading PostGIS extensions into postgres
   CREATE EXTENSION
   CREATE EXTENSION
   CREATE EXTENSION
   CREATE EXTENSION
   
   waiting for server to shut down....2022-06-06 09:33:26.107 UTC [48] LOG:  received fast shutdown request
   ```

2022-06-06 10:21 UTC, strk requested changes
The effects of the change are STILL a "reconnection", so why dropping the comment ? I'd keep the comment to make sure it doesn't break in the future.

Also, you did not specify WHY the `\c` reconnection failed for you (did it fail for you?). Asking an already running process to reconnect would be faster than quitting the process and starting a new one...

2022-06-06 15:08 UTC, sanak commented
@strk Thanks for the comments.

> The effects of the change are STILL a "reconnection", so why dropping the comment ? I'd keep the comment to make sure it doesn't break in the future.

Okay, sure.
Sorry for dropping the comment... 🙇

> Also, you did not specify WHY the \c reconnection failed for you (did it fail for you?). Asking an already running process to reconnect would be faster than quitting the process and starting a new one...

The reproducible step is a bit complex, but it is as follows.

1. Clone docker-gtt (https://github.com/gtt-project/docker-gtt) working branch (`feature/simplify-docker-settings`) on the PR (https://github.com/gtt-project/docker-gtt/pull/53)
   ```bash
   git clone git@github.com:gtt-project/docker-gtt.git -b feature/simplify-docker-settings
   cd docker-gtt
   ```
3. Copy `.env.example` to `.env`, then execute `docker-compose up`.
   ```bash
   copy .env.example .env
   docker-compose up
   ```
5. Confirm that redmine service's migration process starts before postgis service's database init process.
   ```
   redmine_1  | Unknown database adapter `postgis` found in config/database.yml, use Gemfile.local to load your own database gems
   redmine_1  | Your Gemfile lists the gem puma (>= 0) more than once.
   redmine_1  | You should probably keep only one of them.
   redmine_1  | Remove any duplicate entries and specify the gem only once.
   redmine_1  | While it's not a problem now, it could cause errors if you change the version of one of them later.
   redmine_1  | Your Gemfile lists the gem immutable-struct (>= 0) more than once.
   redmine_1  | You should probably keep only one of them.
   redmine_1  | Remove any duplicate entries and specify the gem only once.
   redmine_1  | While it's not a problem now, it could cause errors if you change the version of one of them later.
   redmine_1  | The Gemfile's dependencies are satisfied
   redmine_1  | Unknown database adapter `postgis` found in config/database.yml, use Gemfile.local to load your own database gems
   postgis_1  | The files belonging to this database system will be owned by user "postgres".
   postgis_1  | This user must also own the server process.
   postgis_1  | 
   postgis_1  | The database cluster will be initialized with locale "en_US.utf8".
   postgis_1  | The default database encoding has accordingly been set to "UTF8".
   postgis_1  | The default text search configuration will be set to "english".
   postgis_1  | 
   postgis_1  | Data page checksums are disabled.
   postgis_1  | 
   postgis_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
   postgis_1  | creating subdirectories ... ok
   postgis_1  | selecting dynamic shared memory implementation ... posix
   postgis_1  | selecting default max_connections ... 100
   postgis_1  | selecting default shared_buffers ... 128MB
   postgis_1  | selecting default time zone ... Etc/UTC
   postgis_1  | creating configuration files ... ok
   postgis_1  | running bootstrap script ... ok
   redmine_1  | Unknown database adapter `postgis` found in config/database.yml, use Gemfile.local to load your own database gems
   redmine_1  | rake aborted!
   redmine_1  | ActiveRecord::ConnectionNotEstablished: could not connect to server: Connection refused
   redmine_1  | 	Is the server running on host "postgis" (172.24.0.2) and accepting
   redmine_1  | 	TCP/IP connections on port 5432?
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
   redmine_1  | /usr/local/bundle/gems/activerecord-postgis-adapter-7.1.1/lib/active_record/connection_adapters/postgis/create_connection.rb:41:in `postgis_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_handling.rb:283:in `connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <top (required)>'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/railties/databases.rake:90:in `each'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <top (required)>'
   redmine_1  | 
   redmine_1  | Caused by:
   redmine_1  | PG::ConnectionBad: could not connect to server: Connection refused
   redmine_1  | 	Is the server running on host "postgis" (172.24.0.2) and accepting
   redmine_1  | 	TCP/IP connections on port 5432?
   redmine_1  | /usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
   redmine_1  | /usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `new'
   redmine_1  | /usr/local/bundle/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/postgresql_adapter.rb:78:in `new_client'
   redmine_1  | /usr/local/bundle/gems/activerecord-postgis-adapter-7.1.1/lib/active_record/connection_adapters/postgis/create_connection.rb:41:in `postgis_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
   redmine_1  | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/connection_handling.rb:327:in `retrieve_connec [...]

2022-06-06 19:57 UTC, strk commented
I'm not understanding how this "waiting for service" is at all related
to using `\c` in the SQL stream. The long explanation did not explain
why `\c` could not be used.

2022-06-07 00:03 UTC, sanak commented
@ImreSamu  
Okay, thanks for the information.
I will try to use external IP in `docker-gtt` - `docker-compose.yml` side.

@strk 
> I'm not understanding how this "waiting for service" is at all related
> to using `\c` in the SQL stream. The long explanation did not explain
> why `\c` could not be used.

Okay, sure.
I actually don't know why the error happen when using `\c`, and investigating the cause may take a certain time, so I will try @ImreSamu's advice at first.
Sorry for bothering you.

2022-06-07 00:51 UTC, sanak commented
@ImreSamu  
Thanks!
Using external IP in `docker-gtt` - `docker-compose.yml` healthcheck solved the issue.
commit diff: https://github.com/gtt-project/docker-gtt/pull/53/commits/6bbff06f532efbb27fda79540526f6306ab1b0e0

I close this PR with issue #296.

2022-06-07 00:51 UTC, closed without merging